spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root  # ← 네가 설치할 때 설정한 root 비번!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - profile
              - email

server:
  port: 8080
  servlet:
    session:
      timeout: 30m   #세션 만료 시간

custom:
  jwt:
    secretKey: your-secret-key-goes-here
    access-token-exp: 3600       # 1시간
    refresh-token-exp: 14515200    # 6개월
