spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: coupscoups08  # ← 네가 설치할 때 설정한 root 비번!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
